version: "3.8"

services:
  api:
    build: .
    container_name: go-api-server
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/exchange?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    restart: always # Reinicia se falhar

  db:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: exchange
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck: # Adiciona um healthcheck para garantir que o banco está pronto
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 3s

volumes:
  pgdata:
